import { Incident } from '../types';

export const demoIncidents: Incident[] = [
  {
    id: 'TL-2026-DEMO-01',
    type: 'phishing',
    title: 'Bank KYC Deactivation Phishing SMS',
    description: 'Received SMS: "Dear Customer, Your SBI net banking will be deactivated today. Update PAN immediately to avoid suspension: http://sbi-kyc-verify-portal.in"',
    risk_level: 'HIGH',
    status: 'RESOLVED',
    platform: 'SMS / Android',
    created_at: '2026-09-26T14:32:00Z',
    updated_at: '2026-09-26T15:10:00Z',
    evidence: [
      {
        id: 'ev-demo-1',
        incident_id: 'TL-2026-DEMO-01',
        type: 'screenshot',
        title: 'SMS Message Screenshot',
        file_name: 'sms_sender_alert.png',
        notes: 'Sender ID displayed as VM-SBIBNK with fake web address.',
        created_at: '2026-09-26T14:35:00Z',
      },
      {
        id: 'ev-demo-2',
        incident_id: 'TL-2026-DEMO-01',
        type: 'url',
        title: 'Suspicious Domain Link',
        file_name: 'http://sbi-kyc-verify-portal.in',
        notes: 'Deceptive typosquatting domain impersonating official banking portal.',
        created_at: '2026-09-26T14:38:00Z',
      },
    ],
    timeline: [
      {
        id: 'tl-d1-1',
        incident_id: 'TL-2026-DEMO-01',
        event_type: 'initial_contact',
        title: 'Phishing SMS received',
        description: 'Coercive SMS received claiming immediate KYC suspension.',
        timestamp: '02:32 PM',
      },
      {
        id: 'tl-d1-2',
        incident_id: 'TL-2026-DEMO-01',
        event_type: 'reported_to_threatlens',
        title: 'Analyzed with ThreatLens',
        description: 'URL flagged for credential harvesting and deceptive domain.',
        timestamp: '02:35 PM',
      },
      {
        id: 'tl-d1-3',
        incident_id: 'TL-2026-DEMO-01',
        event_type: 'account_secured',
        title: 'Sender blocked & reported to Chakshu (DoT)',
        description: 'Number reported on Indian DoT Sanchar Saathi / Chakshu facility.',
        timestamp: '03:10 PM',
      },
    ],
    actions: [
      {
        id: 'act-d1-1',
        incident_id: 'TL-2026-DEMO-01',
        priority: 1,
        title: 'Do not click the link or enter credentials',
        description: 'The link directs to an unauthorized third-party credential harvester.',
        is_completed: true,
      },
      {
        id: 'act-d1-2',
        incident_id: 'TL-2026-DEMO-01',
        priority: 2,
        title: 'Report sender to DoT Chakshu portal',
        description: 'Submit SMS sender header VM-SBIBNK to sancharsaathi.gov.in/sfc/.',
        is_completed: true,
        official_link: 'https://sancharsaathi.gov.in/sfc/',
      },
    ],
    analysis: {
      id: 'AN-DEMO-01',
      incident_id: 'TL-2026-DEMO-01',
      analysis_type: 'phishing',
      risk_level: 'HIGH',
      confidence: 94,
      summary: 'Deceptive bank impersonation detected using high-pressure KYC deadlines.',
      findings: [
        'Urgent threat of account deactivation designed to trigger anxiety',
        'Unauthorized domain (sbi-kyc-verify-portal.in) not owned by State Bank of India',
        'Direct solicitation of sensitive banking credentials (PAN / NetBanking)',
      ],
      recommendations: [
        'Do not visit the URL or submit any credentials.',
        'Official SBI domains always terminate in sbi.co.in or onlinesbi.sbi.',
        'Delete SMS and block sender.',
      ],
      technical_signals: {
        domain: 'sbi-kyc-verify-portal.in',
        entropy: 'High',
        sslCert: 'Free Let\'s Encrypt proxy',
      },
      disclaimer: 'DEMO / FICTIONAL DATA for hackathon evaluation.',
      created_at: '2026-09-26T14:35:00Z',
    },
  },
  {
    id: 'TL-2026-DEMO-02',
    type: 'media_forensics',
    title: 'Manipulated Video Call (Deepfake CEO Impersonation)',
    description: 'An executive video message instructing urgent wire transfer for an overseas vendor contract.',
    risk_level: 'HIGH',
    status: 'IN_PROGRESS',
    platform: 'WhatsApp Video',
    created_at: '2026-09-27T08:15:00Z',
    updated_at: '2026-09-27T08:30:00Z',
    evidence: [
      {
        id: 'ev-demo-3',
        incident_id: 'TL-2026-DEMO-02',
        type: 'media',
        title: 'Suspicious MP4 Video Clip',
        file_name: 'urgent_exec_instruction.mp4',
        file_size: 4200000,
        notes: 'Noticeable robotic cadence and unnatural blinking pauses during sentence transitions.',
        created_at: '2026-09-27T08:18:00Z',
      },
    ],
    timeline: [
      {
        id: 'tl-d2-1',
        incident_id: 'TL-2026-DEMO-02',
        event_type: 'threat_received',
        title: 'Video message received',
        description: 'Employee received urgent video message asking for wire transfer authorization.',
        timestamp: '08:15 AM',
      },
      {
        id: 'tl-d2-2',
        incident_id: 'TL-2026-DEMO-02',
        event_type: 'reported_to_threatlens',
        title: 'Forensic scan executed',
        description: 'ThreatLens detected 87% manipulation likelihood with face perimeter warping.',
        timestamp: '08:20 AM',
      },
      {
        id: 'tl-d2-3',
        incident_id: 'TL-2026-DEMO-02',
        event_type: 'bank_notified',
        title: 'Transfer halted internally',
        description: 'Verified with executive via direct landline; fake confirmed.',
        timestamp: '08:28 AM',
      },
    ],
    actions: [
      {
        id: 'act-d2-1',
        incident_id: 'TL-2026-DEMO-02',
        priority: 1,
        title: 'Do not transfer any corporate or personal funds',
        description: 'Confirm the identity of the person via verified secondary communications.',
        is_completed: true,
      },
      {
        id: 'act-d2-2',
        incident_id: 'TL-2026-DEMO-02',
        priority: 2,
        title: 'Retain raw video file for corporate forensic analysis',
        description: 'Do not compress or screen-record; preserve original media file.',
        is_completed: false,
      },
    ],
    analysis: {
      id: 'AN-DEMO-02',
      incident_id: 'TL-2026-DEMO-02',
      analysis_type: 'media_forensics',
      risk_level: 'HIGH',
      confidence: 87,
      summary: 'ThreatLens detected biometric warping and audio-visual neural synthesis patterns.',
      findings: [
        'Facial boundary warping and irregular eye-reflection highlights detected',
        'Discontinuous lighting angles between face and surrounding scene physics',
        'Temporal frame-to-frame inconsistencies along neck and jaw boundaries',
        'Missing original camera hardware EXIF metadata',
      ],
      recommendations: [
        'Verify identity over known phone call before authorizing any payment',
        'Never forward the deepfake media in public groups',
        'File report on cybercrime.gov.in if corporate extortion is attempted',
      ],
      disclaimer: 'AI-generated media detection is not perfect. Treat this result as an indicator, not absolute proof. DEMO / FICTIONAL DATA.',
      created_at: '2026-09-27T08:20:00Z',
    },
  },
  {
    id: 'TL-2026-DEMO-03',
    type: 'scam',
    title: 'UPI QR Code Refund Trap (₹15,000 Transfer Loss)',
    description: 'Seller on OLX sent a QR code stating "Scan to receive payment for your furniture". Entering UPI PIN debited ₹15,000 from citizen account.',
    risk_level: 'CRITICAL',
    status: 'IN_PROGRESS',
    financial_loss: 15000,
    currency: 'INR',
    platform: 'OLX / PhonePe UPI',
    created_at: '2026-09-25T11:20:00Z',
    updated_at: '2026-09-25T12:05:00Z',
    evidence: [
      {
        id: 'ev-demo-4',
        incident_id: 'TL-2026-DEMO-03',
        type: 'screenshot',
        title: 'UPI Debit Alert & UTR Reference',
        file_name: 'phonepe_debit_utr.png',
        notes: 'UTR: 326798124982 - Recipient VPA: merchantpay.982@okaxis',
        created_at: '2026-09-25T11:22:00Z',
      },
      {
        id: 'ev-demo-5',
        incident_id: 'TL-2026-DEMO-03',
        type: 'screenshot',
        title: 'OLX Chat Transcript',
        file_name: 'olx_buyer_chat.png',
        notes: 'Buyer claimed to be an Army officer moving to town; demanded instant QR scan.',
        created_at: '2026-09-25T11:25:00Z',
      },
    ],
    timeline: [
      {
        id: 'tl-d3-1',
        incident_id: 'TL-2026-DEMO-03',
        event_type: 'initial_contact',
        title: 'OLX buyer inquiry',
        description: 'Perpetrator agreed to buy furniture without bargaining.',
        timestamp: '11:10 AM',
      },
      {
        id: 'tl-d3-2',
        incident_id: 'TL-2026-DEMO-03',
        event_type: 'money_transferred',
        title: '₹15,000 debited via QR scan',
        description: 'Perpetrator claimed entering UPI PIN is required to credit seller.',
        timestamp: '11:20 AM',
      },
      {
        id: 'tl-d3-3',
        incident_id: 'TL-2026-DEMO-03',
        event_type: 'reported_to_threatlens',
        title: 'Incident created on ThreatLens',
        description: 'Golden Hour containment checklist generated.',
        timestamp: '11:25 AM',
      },
      {
        id: 'tl-d3-4',
        incident_id: 'TL-2026-DEMO-03',
        event_type: 'bank_notified',
        title: 'Bank fraud division alerted',
        description: 'HDFC Bank fraud desk informed with UTR 326798124982.',
        timestamp: '11:45 AM',
      },
    ],
    actions: [
      {
        id: 'act-d3-1',
        incident_id: 'TL-2026-DEMO-03',
        priority: 1,
        title: 'Call 1930 Cyber Helpline & Bank within Golden Hour',
        description: 'Request immediate freeze of recipient VPA merchantpay.982@okaxis.',
        is_completed: true,
        urgent: true,
        official_link: 'tel:1930',
      },
      {
        id: 'act-d3-2',
        incident_id: 'TL-2026-DEMO-03',
        priority: 2,
        title: 'Lodge formal complaint at cybercrime.gov.in',
        description: 'Submit UTR: 326798124982 and chat screenshots.',
        is_completed: false,
        urgent: true,
        official_link: 'https://cybercrime.gov.in',
      },
      {
        id: 'act-d3-3',
        incident_id: 'TL-2026-DEMO-03',
        priority: 3,
        title: 'Change UPI MPIN & review linked accounts',
        description: 'Reset PhonePe/GPay security PIN on your primary mobile device.',
        is_completed: true,
      },
    ],
    analysis: {
      id: 'AN-DEMO-03',
      incident_id: 'TL-2026-DEMO-03',
      analysis_type: 'scam',
      risk_level: 'CRITICAL',
      confidence: 96,
      summary: 'Classic UPI reverse-charge QR deception resulting in unauthorized funds debit.',
      findings: [
        'Perpetrator exploited common confusion: Scanning a QR code and entering a PIN ALWAYS pays out money, never receives money',
        'Impersonation of armed forces or official buyer to establish false trust',
        'Direct financial debit of ₹15,000 completed via UPI gateway',
      ],
      recommendations: [
        'REMEMBER: You NEVER need to enter your UPI PIN to receive money',
        'Contact your bank immediately to log a chargeback dispute',
        'Do not engage in follow-up calls promising "we will refund by scanning again"',
      ],
      disclaimer: 'DEMO / FICTIONAL DATA for hackathon evaluation.',
      created_at: '2026-09-25T11:25:00Z',
    },
  },
  {
    id: 'TL-2026-DEMO-04',
    type: 'blackmail',
    title: 'Instagram Video Call Sextortion / Extortion Attempt',
    description: 'Blackmailer recorded an intimate video call snippet and threatened to distribute it to Instagram followers unless ₹25,000 is sent in crypto.',
    risk_level: 'CRITICAL',
    status: 'IN_PROGRESS',
    platform: 'Instagram Direct / Telegram',
    created_at: '2026-09-27T01:40:00Z',
    updated_at: '2026-09-27T02:00:00Z',
    evidence: [
      {
        id: 'ev-demo-6',
        incident_id: 'TL-2026-DEMO-04',
        type: 'screenshot',
        title: 'Blackmailer Threat Screenshot',
        file_name: 'extortion_threat_chat.png',
        notes: 'Handle: @maya_k_9912 threatening to message victim\'s brother and college friends.',
        created_at: '2026-09-27T01:42:00Z',
      },
    ],
    timeline: [
      {
        id: 'tl-d4-1',
        incident_id: 'TL-2026-DEMO-04',
        event_type: 'threat_received',
        title: 'Extortion messages received',
        description: 'Demanded ₹25,000 within 2 hours or threat to send media to friends list.',
        timestamp: '01:40 AM',
      },
      {
        id: 'tl-d4-2',
        incident_id: 'TL-2026-DEMO-04',
        event_type: 'reported_to_threatlens',
        title: 'ThreatLens Emergency Plan Generated',
        description: 'Non-payment & immediate evidence lock guidance provided.',
        timestamp: '01:45 AM',
      },
    ],
    actions: [
      {
        id: 'act-d4-1',
        incident_id: 'TL-2026-DEMO-04',
        priority: 1,
        title: 'Do NOT pay any money or send further messages',
        description: 'Paying proves you can be extorted and always results in higher subsequent demands.',
        is_completed: true,
        urgent: true,
      },
      {
        id: 'act-d4-2',
        incident_id: 'TL-2026-DEMO-04',
        priority: 2,
        title: 'Preserve all chat transcripts & account handles',
        description: 'Take full uncropped screenshots including follower list screenshots and profile URL.',
        is_completed: true,
        urgent: true,
      },
      {
        id: 'act-d4-3',
        incident_id: 'TL-2026-DEMO-04',
        priority: 3,
        title: 'Hash imagery on StopNCII.org',
        description: 'Create a non-reversible cryptographic hash on StopNCII.org to prevent automated uploads on Instagram and Facebook.',
        is_completed: false,
        urgent: true,
        official_link: 'https://stopncii.org',
      },
      {
        id: 'act-d4-4',
        incident_id: 'TL-2026-DEMO-04',
        priority: 4,
        title: 'Lock down social media accounts to Private',
        description: 'Set Instagram/Facebook to Private, restrict messages to "Only people you follow", and disable follower visibility if possible.',
        is_completed: false,
      },
      {
        id: 'act-d4-5',
        incident_id: 'TL-2026-DEMO-04',
        priority: 5,
        title: 'Lodge complaint with Cyber Police (1930 / cybercrime.gov.in)',
        description: 'Report under Cyber Crime Against Women & Children (or extortion category) on cybercrime.gov.in.',
        is_completed: false,
        official_link: 'https://cybercrime.gov.in',
      },
    ],
    analysis: {
      id: 'AN-DEMO-04',
      incident_id: 'TL-2026-DEMO-04',
      analysis_type: 'blackmail',
      risk_level: 'CRITICAL',
      confidence: 96,
      summary: 'High-urgency digital blackmail / sextortion threat. Strict non-payment and platform hash protection advised.',
      findings: [
        'Threat to distribute private media to family / friends list',
        'Coercive financial countdown timer to cause acute panic',
        'Account access is still retained by user',
      ],
      recommendations: [
        'Rule 1: Never pay. Payment does not delete the video; it only guarantees further extortion.',
        'Use StopNCII.org to block the media from being shared on major social platforms without exposing the file.',
        'Block and report the account once evidence is saved.',
      ],
      disclaimer: 'DEMO / FICTIONAL DATA for hackathon evaluation.',
      created_at: '2026-09-27T01:45:00Z',
    },
  },
];
