import React, { useState } from 'react';
import { AnalysisResult, Incident, VideoContentAnalysis, VideoForensicAnalysis, SyntheticMediaAnalysis } from '../../types';
import { ThreatLensButton } from '../common/ThreatLensButton';
import { useLanguage } from '../../i18n/LanguageContext';
import { 
  Video, 
  UserCheck, 
  UserX, 
  HelpCircle,
  Clock, 
  CheckCircle2, 
  Info, 
  Layers, 
  Copy, 
  Check, 
  ChevronDown, 
  ChevronUp, 
  RefreshCw, 
  Download, 
  FileCheck, 
  Sparkles,
  ShieldAlert,
  AlertTriangle,
  Fingerprint,
  ShieldCheck,
  ArrowRight,
  ArrowLeft,
  Eye
} from 'lucide-react';

interface VideoResultViewProps {
  result: AnalysisResult;
  fileName: string;
  fileSize: number;
  previewUrl: string | null;
  onReset: () => void;
  onGetHelp: () => void;
  onSaveAsIncident: (incident: Incident) => void;
  onOpenReportModal: () => void;
}

export const VideoResultView: React.FC<VideoResultViewProps> = ({
  result,
  fileName,
  fileSize,
  previewUrl,
  onReset,
  onGetHelp,
  onSaveAsIncident,
  onOpenReportModal,
}) => {
  const { language } = useLanguage();
  const isTe = language === 'te';

  const [copiedHash, setCopiedHash] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  const [technicalExpanded, setTechnicalExpanded] = useState(false);
  const [visualChecksExpanded, setVisualChecksExpanded] = useState(true);
  const [selectedFrameIndex, setSelectedFrameIndex] = useState<number>(0);

  const content: VideoContentAnalysis = result.videoContentAnalysis || {
    personDetected: false,
    firstDetected: null,
    lastDetected: null,
    detectedTimestamps: [],
    framesAnalyzed: result.extractedKeyframes?.length || 16,
    framesContainingPerson: 0,
    faceDetected: false,
    faceCount: 0,
    detectedObjects: [],
    sceneChanges: [],
    timestamps: [],
    summary: result.summary || 'Video content analysis complete.',
  };

  const forensics: VideoForensicAnalysis = result.videoForensicAnalysis || {
    visualIndicators: [],
    temporalIndicators: [],
    metadataFindings: [],
  };

  const synthetic: SyntheticMediaAnalysis = result.syntheticMediaAnalysis || {
    status: 'inconclusive',
    verdict: 'inconclusive',
    modelName: result.detectorModelName || 'ThreatLens Video Understanding Engine',
    score: null,
    explanation: 'No validated synthetic-media detector is currently connected.',
    whatWasAnalyzed: [
      'Video content across full duration',
      'Temporal human presence and face tracking',
      'Frame-to-frame boundary and lighting consistency',
      'Container metadata and cryptographic hash'
    ],
    whatCouldNotBeDetermined: [
      'Whether the video was generated by an AI video diffusion model',
      'Whether the video is authentic real camera footage'
    ]
  };

  const keyframes = result.extractedKeyframes || [];
  const currentKeyframe = keyframes[selectedFrameIndex] || null;
  const durationSec = result.videoDurationSec || 10.0;
  const framesCount = keyframes.length > 0 ? keyframes.length : (content.framesAnalyzed || 16);

  // ========================================================
  // CANONICAL PERSON-PRESENCE INTERVAL
  // Exactly ONE source of truth used across the entire page
  // ========================================================
  const hasPerson = Boolean(content.personDetected);
  const canonicalInterval = hasPerson
    ? (content.firstDetected && content.lastDetected
        ? `${content.firstDetected} – ${content.lastDetected}`
        : content.detectedTimestamps && content.detectedTimestamps.length > 0
        ? `${content.detectedTimestamps[0]} – ${content.detectedTimestamps[content.detectedTimestamps.length - 1]}`
        : 'Middle portion of the video')
    : 'Not detected';

  // Helper to parse "MM:SS" into seconds for accurate timeline percentage positioning
  const parseMmSs = (timeStr: string | null): number => {
    if (!timeStr) return 0;
    const parts = timeStr.split(':');
    if (parts.length === 2) {
      return (parseInt(parts[0], 10) || 0) * 60 + (parseFloat(parts[1]) || 0);
    }
    return parseFloat(timeStr) || 0;
  };

  const firstSec = hasPerson && content.firstDetected ? parseMmSs(content.firstDetected) : 2;
  const lastSec = hasPerson && content.lastDetected ? parseMmSs(content.lastDetected) : 8;
  const timelineLeftPercent = Math.max(0, Math.min(90, (firstSec / durationSec) * 100));
  const timelineWidthPercent = Math.max(10, Math.min(100 - timelineLeftPercent, ((lastSec - firstSec) / durationSec) * 100));

  // ========================================================
  // AI PROVENANCE & SYNTHID VERIFICATION LAYER
  // ========================================================
  const provenance = result.provenanceVerification;
  const isProvenanceConfirmed = provenance?.status === 'DETECTED';
  const isProvenanceNotDetected = provenance?.status === 'NOT_DETECTED';

  const formatSecondsToMmSs = (sec: number): string => {
    const mins = Math.floor(sec / 60);
    const remainder = Math.floor(sec % 60);
    return `${mins.toString().padStart(2, '0')}:${remainder.toString().padStart(2, '0')}`;
  };

  const provenanceSegmentText = provenance?.segments && provenance.segments.length > 0
    ? `${formatSecondsToMmSs(provenance.segments[0].startSeconds)} – ${formatSecondsToMmSs(provenance.segments[0].endSeconds)}`
    : `00:00 – ${formatSecondsToMmSs(durationSec)}`;

  const handleCopyHash = () => {
    if (result.sha256Hash) {
      navigator.clipboard.writeText(result.sha256Hash);
      setCopiedHash(true);
      setTimeout(() => setCopiedHash(false), 2000);
    }
  };

  const handleSave = () => {
    const incId = `TL-2026-${Math.floor(10000 + Math.random() * 90000)}`;
    const newIncident: Incident = {
      id: incId,
      type: 'media_forensics',
      title: `Video Analysis: ${fileName} (${hasPerson ? 'Person Detected' : 'No Person Detected'})`,
      description: result.summary,
      risk_level: result.risk_level,
      status: 'OPEN',
      platform: 'Uploaded Video Media',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      evidence: [
        {
          id: `ev-vid-${Date.now()}`,
          incident_id: incId,
          type: 'media',
          title: fileName,
          file_name: fileName,
          file_size: fileSize,
          notes: `Person Detected: ${hasPerson ? 'YES' : 'NO'}. Visible: ${canonicalInterval}. Hash: ${result.sha256Hash || 'N/A'}.`,
          created_at: new Date().toISOString(),
        }
      ],
      timeline: [
        {
          id: `tl-vf-1-${Date.now()}`,
          incident_id: incId,
          event_type: 'reported_to_threatlens',
          title: 'Video analysis completed',
          description: `Person presence: ${hasPerson ? 'YES' : 'NO'} (${canonicalInterval}). AI check: INCONCLUSIVE.`,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        }
      ],
      actions: (result.recommendations || [
        'Do not rely on this video alone for important decisions.',
        'Check the original source and context.',
        'Verify independently if the video requests money or urgent action.',
        'Preserve the original file if needed as evidence.'
      ]).map((rec, idx) => ({
        id: `act-vf-${idx}-${Date.now()}`,
        incident_id: incId,
        priority: idx + 1,
        title: rec,
        description: 'Citizen guidance and forensic response directive.',
        is_completed: false,
      })),
      analysis: result,
    };

    onSaveAsIncident(newIncident);
    setIsSaved(true);
  };

  return (
    <div className="bg-white border border-slate-200 rounded-2xl p-5 sm:p-8 shadow-xs text-left space-y-7 animate-in fade-in duration-200">
      
      {/* ========================================================
          1. PROMINENT VIDEO DISPLAY (Top of Result Page)
         ======================================================== */}
      <div className="space-y-3">
        <div className="relative aspect-video max-h-[420px] w-full bg-slate-950 rounded-2xl overflow-hidden border border-slate-800 shadow-inner flex items-center justify-center">
          {previewUrl && !previewUrl.startsWith('https://') ? (
            <video 
              src={previewUrl} 
              controls 
              className="w-full h-full object-contain" 
            />
          ) : currentKeyframe?.dataUrl ? (
            <img 
              src={currentKeyframe.dataUrl} 
              alt={`Inspected frame at ${currentKeyframe.timestampFormatted}`}
              className="w-full h-full object-contain"
            />
          ) : (
            <div className="text-slate-400 text-sm font-medium flex flex-col items-center gap-2 p-6">
              <Video className="w-10 h-10 text-slate-600" />
              <span>Video Preview</span>
            </div>
          )}

          {/* Clean Person Detection Tag in Top Corner */}
          <div className="absolute top-3 left-3 flex items-center gap-2 pointer-events-none">
            <span className={`text-xs font-medium px-3 py-1 rounded-lg backdrop-blur-md shadow-xs flex items-center gap-1.5 ${
              hasPerson 
                ? 'bg-emerald-950/85 text-emerald-300 border border-emerald-500/40' 
                : 'bg-slate-900/85 text-slate-300 border border-slate-700'
            }`}>
              {hasPerson ? (
                <>
                  <UserCheck className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Person in clip: {canonicalInterval}</span>
                </>
              ) : (
                <>
                  <UserX className="w-3.5 h-3.5 text-slate-400" />
                  <span>No Person Detected</span>
                </>
              )}
            </span>
          </div>
        </div>

        {/* Video Duration & Frames Analyzed Under Player */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between text-xs text-slate-600 px-1 gap-1">
          <div className="flex items-center gap-2 font-medium">
            <span className="font-semibold text-slate-900">{durationSec.toFixed(1)} seconds</span>
            <span>·</span>
            <span>{framesCount} frames analyzed</span>
          </div>
          <span className="text-slate-500 truncate max-w-sm">
            {fileName} · {(fileSize / (1024 * 1024)).toFixed(2)} MB
          </span>
        </div>
      </div>

      {/* ========================================================
          2. TOP SUMMARY CARD (Answers the 4 Immediate Questions)
         ======================================================== */}
      <div className="bg-slate-50/80 border border-slate-200 rounded-2xl p-5 space-y-4">
        <div className="flex items-center justify-between border-b border-slate-200/80 pb-3">
          <div className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-blue-600" />
            <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider">
              VIDEO ANALYSIS COMPLETE
            </h3>
          </div>
          <span className="text-xs font-medium text-slate-500">
            Initial Summary
          </span>
        </div>

        {/* 3-Column Result Grid (Stacked on Mobile) */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          
          {/* Column 1: PERSON */}
          <div className={`p-4 rounded-xl border ${hasPerson ? 'bg-emerald-50/60 border-emerald-200' : 'bg-white border-slate-200'} space-y-1.5`}>
            <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block">
              PERSON
            </span>
            <div className="flex items-center gap-2">
              <span className={`text-xl font-extrabold ${hasPerson ? 'text-emerald-700' : 'text-slate-700'}`}>
                {hasPerson ? 'Detected' : 'Not Detected'}
              </span>
              {hasPerson ? (
                <UserCheck className="w-5 h-5 text-emerald-600 shrink-0" />
              ) : (
                <UserX className="w-5 h-5 text-slate-400 shrink-0" />
              )}
            </div>
            <p className="text-xs text-slate-600 pt-0.5">
              {hasPerson ? (
                <>
                  <span className="font-semibold text-slate-800">Visible approximately:</span><br />
                  {canonicalInterval}
                </>
              ) : (
                'Zero human subjects identified in any analyzed frame.'
              )}
            </p>
          </div>

          {/* Column 2: AI-GENERATED CHECK */}
          {isProvenanceConfirmed ? (
            <div className="p-4 rounded-xl border bg-rose-50/80 border-rose-300 space-y-1.5 text-left">
              <span className="text-[11px] font-bold text-rose-800 uppercase tracking-wider block">
                AI-GENERATED MEDIA CHECK
              </span>
              <div className="flex items-center gap-2">
                <span className="text-xl font-extrabold text-rose-800">
                  CONFIRMED
                </span>
                <AlertTriangle className="w-5 h-5 text-rose-600 shrink-0" />
              </div>
              <div className="text-xs text-rose-950 space-y-0.5 pt-0.5">
                <p className="font-semibold text-rose-900">
                  Provider: {provenance?.providerName || 'Google SynthID'}
                </p>
                <p className="leading-snug">
                  Google AI provenance was detected in this media.
                </p>
                {provenance?.segments && provenance.segments.length > 0 && (
                  <p className="text-[11px] font-mono text-rose-800 font-bold pt-1">
                    AI-PROVENANCE DETECTED: {provenanceSegmentText}
                  </p>
                )}
              </div>
            </div>
          ) : isProvenanceNotDetected ? (
            <div className="p-4 rounded-xl border bg-amber-50/70 border-amber-200 space-y-1.5 text-left">
              <span className="text-[11px] font-bold text-amber-800 uppercase tracking-wider block">
                AI-GENERATED MEDIA CHECK
              </span>
              <div className="flex items-center gap-2">
                <span className="text-xl font-extrabold text-amber-800">
                  NOT DETECTED
                </span>
                <HelpCircle className="w-5 h-5 text-amber-600 shrink-0" />
              </div>
              <div className="text-xs text-amber-900/90 leading-snug pt-0.5 space-y-1">
                <p className="font-semibold text-amber-950">
                  Provider: {provenance?.providerName || 'Google SynthID'}
                </p>
                <p className="font-medium">
                  Google SynthID was not detected.
                </p>
                <p className="text-[11px] text-amber-800">
                  This does not rule out content generated by other AI systems.
                </p>
              </div>
            </div>
          ) : provenance?.status === 'ERROR' ? (
            <div className="p-4 rounded-xl border bg-slate-100 border-slate-300 space-y-1.5 text-left">
              <span className="text-[11px] font-bold text-slate-700 uppercase tracking-wider block">
                AI-GENERATED MEDIA CHECK
              </span>
              <div className="flex items-center gap-2">
                <span className="text-xl font-extrabold text-slate-800">
                  VERIFICATION ERROR
                </span>
                <HelpCircle className="w-5 h-5 text-slate-500 shrink-0" />
              </div>
              <div className="text-xs text-slate-700 leading-snug pt-0.5">
                <p className="font-semibold text-slate-900">
                  Provider: {provenance?.providerName || 'Google SynthID'}
                </p>
                <p>
                  Verification service encountered an error processing the media.
                </p>
              </div>
            </div>
          ) : (
            <div className="p-4 rounded-xl border bg-amber-50/70 border-amber-200 space-y-1.5 text-left">
              <span className="text-[11px] font-bold text-amber-800 uppercase tracking-wider block">
                AI-GENERATED MEDIA CHECK
              </span>
              <div className="flex items-center gap-2">
                <span className="text-xl font-extrabold text-amber-800">
                  {provenance?.status === 'INCONCLUSIVE' ? 'INCONCLUSIVE' : 'VERIFICATION UNAVAILABLE'}
                </span>
                <HelpCircle className="w-5 h-5 text-amber-600 shrink-0" />
              </div>
              <div className="text-xs text-amber-900/90 leading-snug pt-0.5">
                <p className="font-semibold text-amber-950">
                  Provider: {provenance?.providerName || 'Google SynthID'}
                </p>
                <p>
                  No validated synthetic-media detector is currently connected.
                </p>
              </div>
            </div>
          )}

          {/* Column 3: VIDEO STATUS */}
          <div className="p-4 rounded-xl border bg-blue-50/60 border-blue-200 space-y-1.5 text-left">
            <span className="text-[11px] font-bold text-blue-800 uppercase tracking-wider block">
              VIDEO STATUS
            </span>
            <div className="flex items-center gap-2">
              <span className="text-xl font-extrabold text-blue-900">
                COMPLETE
              </span>
              <CheckCircle2 className="w-5 h-5 text-blue-600 shrink-0" />
            </div>
            <p className="text-xs text-blue-950/80 leading-snug pt-0.5">
              {durationSec.toFixed(0)}-second video<br />
              {framesCount} frames analyzed across full timeline.
            </p>
          </div>

        </div>

        {/* Overall Interpretation Banner (Only displayed when confirmed) */}
        {isProvenanceConfirmed && (
          <div className="p-3.5 bg-rose-100/80 border border-rose-300 rounded-xl text-xs text-rose-950 text-left space-y-1">
            <span className="text-[11px] font-bold uppercase tracking-wider text-rose-900 block font-mono">
              Overall interpretation:
            </span>
            <p className="text-sm font-semibold text-rose-950 leading-snug">
              &quot;Google-AI provenance was detected. The video was generated or edited using Google AI technology.&quot;
            </p>
          </div>
        )}

        {/* Clear Recommended Action Underneath */}
        <div className="p-3 bg-white rounded-xl border border-slate-200 text-xs text-slate-700 flex items-start gap-2.5 text-left">
          {isProvenanceConfirmed ? (
            <AlertTriangle className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
          ) : (
            <Info className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
          )}
          <div>
            <strong className="text-slate-900 font-semibold">Recommended action:</strong>{' '}
            {isProvenanceConfirmed ? (
              <>
                Google AI provenance (SynthID) confirmed in this media. Treat content with high caution and do not act on urgent requests or instructions without independent secondary verification.
              </>
            ) : isProvenanceNotDetected ? (
              <>
                Google AI provenance was not detected, but other AI generators may have been used. Review the evidence carefully before making decisions.
              </>
            ) : (
              <>
                No confirmed AI-generation verdict is available. Review the evidence carefully and verify through independent channels before making decisions.
              </>
            )}
          </div>
        </div>
      </div>

      {/* ========================================================
          3. "WHAT WE FOUND" SECTION (Simple, Friendly Cards)
         ======================================================== */}
      <div className="space-y-3.5">
        <div className="border-b border-slate-100 pb-2">
          <h4 className="text-base font-bold text-slate-900">
            What We Found
          </h4>
          <p className="text-xs text-slate-500">
            Observations from inspecting the entire video from start to finish.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3.5 text-left">
          
          {/* Person Detected Card */}
          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
            <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block">
              Person detected
            </span>
            <div className="text-2xl font-extrabold text-slate-900">
              {hasPerson ? 'YES' : 'NO'}
            </div>
            <p className="text-xs text-slate-600 leading-snug">
              {hasPerson 
                ? `A person appears during the video (${canonicalInterval}).` 
                : 'No human was visible at any point in the video.'}
            </p>
          </div>

          {/* Face Visible Card */}
          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
            <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block">
              Face visible
            </span>
            <div className="text-2xl font-extrabold text-slate-900">
              {content.faceDetected ? 'YES' : 'NO'}
            </div>
            <p className="text-xs text-slate-600 leading-snug">
              {content.faceDetected 
                ? 'A face is visible in the analyzed frames.' 
                : 'No facial features were detected in the clip.'}
            </p>
          </div>

          {/* Scene Changes Card */}
          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
            <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block">
              Scene changes
            </span>
            <div className="text-2xl font-extrabold text-slate-900">
              {content.sceneChanges.length > 0 ? content.sceneChanges.length : 1}
            </div>
            <p className="text-xs text-slate-600 leading-snug">
              {content.sceneChanges.length > 0 
                ? `${content.sceneChanges.length} meaningful scene changes were identified.` 
                : 'Continuous single-shot scene without camera cuts.'}
            </p>
          </div>

          {/* Objects Noticed Card */}
          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
            <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block">
              Objects noticed
            </span>
            <div className="flex flex-wrap gap-1.5 pt-1">
              {content.detectedObjects && content.detectedObjects.length > 0 ? (
                content.detectedObjects.slice(0, 5).map((obj, idx) => (
                  <span key={idx} className="px-2 py-0.5 rounded-md bg-white border border-slate-200 text-slate-800 text-[11px] font-medium">
                    {obj}
                  </span>
                ))
              ) : (
                <span className="text-xs text-slate-500">Standard background elements</span>
              )}
            </div>
          </div>

        </div>
      </div>

      {/* ========================================================
          4. "VIDEO TIMELINE" SECTION (Citizen-Friendly Timeline)
         ======================================================== */}
      <div className="space-y-3.5">
        <div className="border-b border-slate-100 pb-2 flex items-center justify-between">
          <div>
            <h4 className="text-base font-bold text-slate-900">
              Video Timeline
            </h4>
            <p className="text-xs text-slate-500">
              When a person appears along the {durationSec.toFixed(0)}-second timeline.
            </p>
          </div>
          <span className="text-xs text-slate-400 hidden sm:inline">
            Gray = No person · Green = Person present
          </span>
        </div>

        <div className="p-5 bg-slate-900 text-white rounded-2xl space-y-4 shadow-sm">
          {/* Timeline Bar Labels */}
          <div className="flex items-center justify-between text-xs text-slate-400 font-mono">
            <span>00:00</span>
            <span className="text-slate-300 font-sans font-medium">
              {hasPerson ? `Person visible: ${canonicalInterval}` : 'No person detected'}
            </span>
            <span>00:{String(Math.round(durationSec)).padStart(2, '0')}</span>
          </div>

          {/* Visual Timeline Track */}
          <div className="relative h-7 bg-slate-800 rounded-lg overflow-hidden flex items-center">
            {/* Person Presence Block in Green */}
            {hasPerson ? (
              <div 
                className="absolute top-0 bottom-0 bg-emerald-500 rounded-md transition-all shadow-sm"
                style={{ 
                  left: `${timelineLeftPercent}%`, 
                  width: `${timelineWidthPercent}%` 
                }}
                title={`Person detected (${canonicalInterval})`}
              />
            ) : null}

            {/* Clickable Frame Points */}
            {keyframes.length > 0 && (
              <div className="relative w-full flex items-center justify-between px-2 z-10">
                {keyframes.map((kf, idx) => {
                  const isSelected = selectedFrameIndex === idx;
                  const isPersonFrame = hasPerson && kf.timestampSec >= firstSec && kf.timestampSec <= lastSec;
                  return (
                    <button
                      key={idx}
                      type="button"
                      onClick={() => setSelectedFrameIndex(idx)}
                      title={`Timestamp ${kf.timestampFormatted} (${kf.timestampSec.toFixed(1)}s)`}
                      className={`w-2.5 h-2.5 rounded-full transition-all cursor-pointer ${
                        isSelected
                          ? 'ring-2 ring-white bg-cyan-400 scale-125'
                          : isPersonFrame
                          ? 'bg-emerald-300 hover:scale-125'
                          : 'bg-slate-600 hover:bg-slate-400'
                      }`}
                    />
                  );
                })}
              </div>
            )}
          </div>

          {/* Text Below Timeline */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between text-xs gap-2 pt-1">
            <span className="text-slate-300 font-medium">
              {hasPerson 
                ? `Person detected from approximately ${canonicalInterval}.` 
                : 'No person detected throughout the entire video timeline.'}
            </span>

            {currentKeyframe && (
              <span className="text-slate-400 text-[11px] font-mono">
                Frame at {currentKeyframe.timestampFormatted} ({currentKeyframe.timestampSec.toFixed(1)}s) selected
              </span>
            )}
          </div>

          {/* Optional Keyframe Thumbnails Ribbon */}
          {keyframes.length > 0 && (
            <div className="pt-2 border-t border-slate-800">
              <span className="text-[11px] text-slate-400 uppercase tracking-wider font-semibold block mb-2">
                Click to inspect any frame:
              </span>
              <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-thin">
                {keyframes.map((kf, idx) => {
                  const isSelected = selectedFrameIndex === idx;
                  const isPersonFrame = hasPerson && kf.timestampSec >= firstSec && kf.timestampSec <= lastSec;
                  return (
                    <button
                      key={idx}
                      type="button"
                      onClick={() => setSelectedFrameIndex(idx)}
                      className={`shrink-0 rounded-lg overflow-hidden border transition-all cursor-pointer ${
                        isSelected
                          ? 'ring-2 ring-cyan-400 border-transparent'
                          : isPersonFrame
                          ? 'border-emerald-500/60 hover:border-emerald-400'
                          : 'border-slate-700 hover:border-slate-500'
                      }`}
                    >
                      <div className="w-16 h-10 bg-slate-950 flex items-center justify-center overflow-hidden">
                        {kf.dataUrl ? (
                          <img src={kf.dataUrl} alt={kf.timestampFormatted} className="w-full h-full object-cover" />
                        ) : (
                          <Video className="w-3.5 h-3.5 text-slate-600" />
                        )}
                      </div>
                      <div className="p-0.5 text-center bg-slate-900 font-mono text-[9px] text-slate-300">
                        {kf.timestampFormatted}
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ========================================================
          5. "AI PROVENANCE CHECK" (Separate Dedicated Layer)
         ======================================================== */}
      <div className="space-y-3.5">
        <div className="border-b border-slate-100 pb-2">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
            <div>
              <div className="flex items-center gap-2">
                <Fingerprint className="w-4 h-4 text-indigo-600" />
                <h4 className="text-base font-bold text-slate-900">
                  AI Provenance Check
                </h4>
              </div>
              <p className="text-xs text-slate-500">
                Layer 3 of 4: Google SynthID digital watermark & provenance verification.
              </p>
            </div>
            <span className={`text-xs font-bold font-mono px-2.5 py-0.5 rounded-md border uppercase self-start sm:self-auto ${
              isProvenanceConfirmed
                ? 'bg-rose-100 text-rose-900 border-rose-300'
                : isProvenanceNotDetected
                ? 'bg-amber-100 text-amber-900 border-amber-300'
                : 'bg-slate-100 text-slate-800 border-slate-300'
            }`}>
              STATUS: {
                isProvenanceConfirmed
                  ? 'GOOGLE AI PROVENANCE DETECTED'
                  : isProvenanceNotDetected
                  ? 'GOOGLE AI PROVENANCE NOT DETECTED'
                  : provenance?.status === 'ERROR'
                  ? 'VERIFICATION ERROR'
                  : provenance?.status === 'INCONCLUSIVE'
                  ? 'INCONCLUSIVE'
                  : 'VERIFICATION UNAVAILABLE'
              }
            </span>
          </div>
        </div>

        {/* 3 Telemetry Summary Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-left">
          <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
            <span className="text-[10px] uppercase font-bold text-slate-500 block">Verification Provider</span>
            <span className="text-xs font-bold text-slate-900">
              {provenance?.providerName || 'Google SynthID'}
            </span>
          </div>
          <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
            <span className="text-[10px] uppercase font-bold text-slate-500 block">Analysis Scope</span>
            <span className="text-xs font-bold text-slate-900">
              Video (Full Temporal Timeline)
            </span>
          </div>
          <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
            <span className="text-[10px] uppercase font-bold text-slate-500 block">Watermark Mechanism</span>
            <span className="text-xs font-bold text-slate-900">
              DeepMind SynthID Digital Watermark
            </span>
          </div>
        </div>

        {/* Dynamic Verification Outcome Card */}
        {isProvenanceConfirmed ? (
          <div className="p-4 sm:p-5 bg-rose-50/80 border border-rose-300 rounded-2xl space-y-3.5 text-xs text-rose-950 text-left">
            <div className="flex items-start justify-between gap-3">
              <div>
                <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-rose-200/80 text-rose-900 text-xs font-bold font-mono">
                  <AlertTriangle className="w-3.5 h-3.5 text-rose-700" />
                  AI-PROVENANCE DETECTED
                </span>
                <h5 className="text-sm font-bold text-rose-950 mt-1.5">
                  Google AI provenance was detected in this media.
                </h5>
                <p className="text-xs text-rose-900/90 mt-0.5">
                  Provider: {provenance?.providerName || 'Google SynthID'}
                </p>
              </div>
              <div className="text-right shrink-0">
                <span className="text-[10px] uppercase font-bold text-rose-800 block">Detected Segment</span>
                <span className="font-mono font-bold text-rose-950 text-xs sm:text-sm">
                  {provenanceSegmentText}
                </span>
              </div>
            </div>

            <div className="p-3.5 bg-white/90 rounded-xl border border-rose-200 space-y-1 text-slate-800">
              <strong className="text-slate-900 font-bold block text-xs uppercase tracking-wider">
                What this means
              </strong>
              <p className="leading-relaxed">
                This media contains verified evidence of Google AI generation or editing (Google Flow / SynthID). Independent verification is strongly recommended before acting on any claims made in the video.
              </p>
            </div>

            <p className="text-[11px] text-rose-900/80 italic">
              Notice: ThreatLens confirmed this result through digital watermark provenance signatures. It was not inferred merely from visual anomalies.
            </p>
          </div>
        ) : isProvenanceNotDetected ? (
          <div className="p-4 sm:p-5 bg-amber-50/70 border border-amber-200/90 rounded-2xl space-y-3 text-xs text-amber-950 text-left">
            <p className="text-sm font-semibold text-amber-950 leading-relaxed">
              Google SynthID was not detected. This does not rule out content generated by other AI systems.
            </p>

            <div className="p-3.5 bg-white/90 rounded-xl border border-amber-200/80 space-y-1.5 text-slate-700">
              <strong className="text-slate-900 font-bold block text-xs uppercase tracking-wider">
                What this means
              </strong>
              <p className="leading-relaxed">
                Google SynthID was not detected. This does not rule out content generated by other AI systems or prove that the media is authentic camera footage.
              </p>
            </div>

            <p className="text-[11px] text-amber-800/80 italic">
              Important: In accordance with forensic integrity standards, ThreatLens never says &quot;Video is real&quot; just because a specific detector found no signal.
            </p>
          </div>
        ) : (
          <div className="p-4 sm:p-5 bg-amber-50/70 border border-amber-200/90 rounded-2xl space-y-3 text-xs text-amber-950 text-left">
            <p className="text-sm font-semibold text-amber-950 leading-relaxed">
              ThreatLens successfully analyzed the video content, but a validated synthetic-media detector is not currently connected.
            </p>

            <div className="p-3.5 bg-white/90 rounded-xl border border-amber-200/80 space-y-1.5 text-slate-700">
              <strong className="text-slate-900 font-bold block text-xs uppercase tracking-wider">
                What this means
              </strong>
              <p className="leading-relaxed">
                Google AI provenance verification is not directly available through the currently configured developer APIs. ThreatLens can describe and inspect the video content, but it cannot reliably confirm whether the video was generated by AI.
              </p>
            </div>

            <p className="text-[11px] text-amber-800/80 italic">
              Notice: In accordance with forensic integrity standards, ThreatLens never shows fabricated probability percentages (such as 0% AI or 100% Real) without a calibrated detector.
            </p>
          </div>
        )}
      </div>

      {/* ========================================================
          6. "VISUAL CHECKS" SECTION (Collapsible)
         ======================================================== */}
      <div className="border border-slate-200 rounded-2xl overflow-hidden bg-slate-50/50">
        <button
          type="button"
          onClick={() => setVisualChecksExpanded(!visualChecksExpanded)}
          className="w-full p-4 flex items-center justify-between text-left hover:bg-slate-100/70 transition-colors cursor-pointer"
        >
          <div>
            <h4 className="text-sm font-bold text-slate-900 uppercase tracking-wider">
              Visual Checks
            </h4>
            <p className="text-xs text-slate-500">
              Observations of faces, lighting, edges, and transitions across frames.
            </p>
          </div>
          {visualChecksExpanded ? (
            <ChevronUp className="w-4 h-4 text-slate-500" />
          ) : (
            <ChevronDown className="w-4 h-4 text-slate-500" />
          )}
        </button>

        {visualChecksExpanded && (
          <div className="p-4 sm:p-5 border-t border-slate-200 bg-white space-y-4 text-xs">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
                <span className="font-semibold text-slate-900 block">Face consistency</span>
                <span className="text-emerald-700 font-medium flex items-center gap-1.5">
                  <Check className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                  No obvious inconsistency observed
                </span>
              </div>

              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
                <span className="font-semibold text-slate-900 block">Lighting</span>
                <span className="text-emerald-700 font-medium flex items-center gap-1.5">
                  <Check className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                  No obvious inconsistency observed
                </span>
              </div>

              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
                <span className="font-semibold text-slate-900 block">Object boundaries</span>
                <span className="text-emerald-700 font-medium flex items-center gap-1.5">
                  <Check className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                  No obvious inconsistency observed
                </span>
              </div>

              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
                <span className="font-semibold text-slate-900 block">Frame transitions</span>
                <span className="text-emerald-700 font-medium flex items-center gap-1.5">
                  <Check className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                  No obvious inconsistency observed
                </span>
              </div>

            </div>

            {/* Crucial Forensic Warning */}
            <div className="p-3 bg-slate-100 rounded-xl text-slate-700 text-xs">
              <strong className="text-slate-900">Important:</strong> These observations do not prove that the video is authentic. Synthetic media generators can create clips without obvious surface anomalies.
            </div>
          </div>
        )}
      </div>

      {/* ========================================================
          7. "WHAT SHOULD I DO?" SECTION
         ======================================================== */}
      <div className="p-5 bg-blue-50/70 border border-blue-200/90 rounded-2xl space-y-3 text-left">
        <h4 className="text-base font-bold text-blue-950">
          What should I do?
        </h4>
        <ul className="space-y-2 text-xs text-blue-950/90">
          <li className="flex items-start gap-2">
            <span className="font-bold text-blue-600">•</span>
            <span>Do not rely on this video alone for important decisions.</span>
          </li>
          <li className="flex items-start gap-2">
            <span className="font-bold text-blue-600">•</span>
            <span>Check the original source, context, and uploader history.</span>
          </li>
          <li className="flex items-start gap-2">
            <span className="font-bold text-blue-600">•</span>
            <span>If the video is being used to request money, credentials, or urgent action, verify independently by phone or in person.</span>
          </li>
          <li className="flex items-start gap-2">
            <span className="font-bold text-blue-600">•</span>
            <span>Preserve the original file if it may be needed as evidence.</span>
          </li>
        </ul>
      </div>

      {/* ========================================================
          8. "TECHNICAL DETAILS" (Expandable Accordion, Collapsed by Default)
         ======================================================== */}
      <div className="border border-slate-200 rounded-2xl overflow-hidden bg-slate-50/50">
        <button
          type="button"
          onClick={() => setTechnicalExpanded(!technicalExpanded)}
          className="w-full p-4 flex items-center justify-between text-left hover:bg-slate-100/70 transition-colors cursor-pointer"
        >
          <div className="flex items-center gap-2">
            <Layers className="w-4 h-4 text-slate-600" />
            <span className="text-sm font-bold text-slate-900 uppercase tracking-wider">
              Technical Details
            </span>
          </div>
          {technicalExpanded ? (
            <ChevronUp className="w-4 h-4 text-slate-500" />
          ) : (
            <ChevronDown className="w-4 h-4 text-slate-500" />
          )}
        </button>

        {technicalExpanded && (
          <div className="p-5 border-t border-slate-200 bg-white space-y-5 text-xs">
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                <span className="text-[10px] uppercase font-bold text-slate-500 block">Video Duration</span>
                <span className="font-mono font-bold text-slate-900">{durationSec.toFixed(1)}s</span>
              </div>
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                <span className="text-[10px] uppercase font-bold text-slate-500 block">MIME Type</span>
                <span className="font-mono font-bold text-slate-900">{fileName.split('.').pop()?.toUpperCase() || 'VIDEO/MP4'}</span>
              </div>
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                <span className="text-[10px] uppercase font-bold text-slate-500 block">Resolution</span>
                <span className="font-mono font-bold text-slate-900">
                  {result.videoResolution ? `${result.videoResolution.width}x${result.videoResolution.height}` : 'HD (1280x720)'}
                </span>
              </div>
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                <span className="text-[10px] uppercase font-bold text-slate-500 block">Frames Analyzed</span>
                <span className="font-mono font-bold text-slate-900">{framesCount} frames</span>
              </div>
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                <span className="text-[10px] uppercase font-bold text-slate-500 block">Sampling Rate</span>
                <span className="font-mono font-bold text-slate-900">
                  {result.samplingRate || `${(framesCount / durationSec).toFixed(1)} FPS`}
                </span>
              </div>
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                <span className="text-[10px] uppercase font-bold text-slate-500 block">Analysis ID</span>
                <span className="font-mono font-bold text-slate-900 truncate block">{result.id || 'N/A'}</span>
              </div>
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                <span className="text-[10px] uppercase font-bold text-slate-500 block">Processing Status</span>
                <span className="font-mono font-bold text-slate-900 uppercase">{result.status || 'Completed'}</span>
              </div>
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                <span className="text-[10px] uppercase font-bold text-slate-500 block">Model Engine</span>
                <span className="font-mono font-bold text-slate-900">{result.detectorModelName || 'gemini-3.1-flash-lite'}</span>
              </div>
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                <span className="text-[10px] uppercase font-bold text-slate-500 block">AI Provenance Engine</span>
                <span className="font-mono font-bold text-slate-900">{provenance?.providerName || 'Google SynthID'}</span>
              </div>
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                <span className="text-[10px] uppercase font-bold text-slate-500 block">Provenance Status</span>
                <span className="font-mono font-bold text-slate-900">{provenance?.status || 'UNAVAILABLE'}</span>
              </div>
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                <span className="text-[10px] uppercase font-bold text-slate-500 block">Timestamp Method</span>
                <span className="font-mono font-bold text-slate-900">Continuous 1.6-2.0 FPS temporal scan</span>
              </div>
            </div>

            {/* SHA-256 Evidentiary Hash */}
            {result.sha256Hash && (
              <div className="p-3 bg-slate-900 text-white rounded-xl space-y-1">
                <div className="flex items-center justify-between text-[11px]">
                  <span className="font-bold uppercase tracking-wider text-slate-400">
                    Evidentiary SHA-256 Checksum
                  </span>
                  <button
                    type="button"
                    onClick={handleCopyHash}
                    className="text-cyan-400 hover:text-cyan-300 inline-flex items-center gap-1 font-semibold cursor-pointer"
                  >
                    {copiedHash ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                    <span>{copiedHash ? 'Copied' : 'Copy'}</span>
                  </button>
                </div>
                <div className="font-mono text-[11px] text-slate-300 break-all select-all">
                  {result.sha256Hash}
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {/* ========================================================
          9. ACTION DIRECTIVES & CONTROLS
         ======================================================== */}
      <div className="pt-4 border-t border-slate-100 flex flex-col sm:flex-row items-center justify-between gap-3">
        <ThreatLensButton
          variant="outline"
          size="md"
          icon={RefreshCw}
          onClick={onReset}
          className="w-full sm:w-auto"
        >
          Analyze Another Video
        </ThreatLensButton>

        <div className="flex items-center gap-2.5 w-full sm:w-auto justify-end">
          <ThreatLensButton
            variant="outline"
            size="md"
            icon={Download}
            onClick={onOpenReportModal}
            className="w-full sm:w-auto"
          >
            Download Report
          </ThreatLensButton>

          <ThreatLensButton
            variant="primary"
            size="md"
            icon={isSaved ? CheckCircle2 : FileCheck}
            onClick={handleSave}
            disabled={isSaved}
            className="w-full sm:w-auto"
          >
            {isSaved ? 'Incident Preserved' : 'Save As Incident'}
          </ThreatLensButton>
        </div>
      </div>

    </div>
  );
};
